### ISSUE TITLE
Mocha sample with Elmish.React stub

### ISSUE THREAD

**Issue by aolney** [fable-compiler/fable2-samples#14]
With latest React, there seems to be an [issue with requestAnimationFrame](https://github.com/One-com/react-truncate/issues/60).

To use mocha with Elmish.React, I needed to [install a stub package](https://github.com/alexreardon/raf-stub), [create a test-setup.js file](https://github.com/alexreardon/raf-stub#full-mocha-end-to-end-setup), and change my package.json line to `"test": "mocha test-build -r jsdom-global/register -t 10000  --require tests/test-setup.js"`

This is not a bug in the current sample but may suggest an additional sample using Elmish.

**Comment by alfonsogarciacaro** [comment]
Hmm, not sure if related, but you can use `Program.withReactSynchronous` to avoid `requestAnimationFrame`.

**Comment by aolney** [comment]
Thanks for that tip - was using `withReactBatched`

However, changing to `withReactSynchronous` seems to cause another error, keeping the mocha line as above:

```
> mocha test-build -r jsdom-global/register -t 10000  --require tests/test-setup.js

/z/aolney/repos/question-classifier-2003-reboot/node_modules/yargs/yargs.js:1163
      else throw err
           ^

Invariant Violation: Target container is not a DOM element.
    at invariant (/z/aolney/repos/question-classifier-2003-reboot/node_modules/react-dom/cjs/react-dom.development.js:55:15)
    at Object.render (/z/aolney/repos/question-classifier-2003-reboot/node_modules/react-dom/cjs/react-dom.development.js:21151:36)
    at Elmish_Program.setState$$1 [as setState] (/z/aolney/repos/question-classifier-2003-reboot/test-build/Fable.Elmish.React.3.0.1/react.js:46:19)
    at ProgramModule$$$runWith (/z/aolney/repos/question-classifier-2003-reboot/test-build/Fable.Elmish.3.0.0/program.js:187:15)
    at ProgramModule$$$run (/z/aolney/repos/question-classifier-2003-reboot/test-build/Fable.Elmish.3.0.0/program.js:201:3)
    at Object.<anonymous> (/z/aolney/repos/question-classifier-2003-reboot/test-build/src/App.js:237:34)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/z/aolney/repos/question-classifier-2003-reboot/test-build/Tests.js:28:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/mocha.js:330:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/mocha.js:327:14)
    at Mocha.run (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/mocha.js:804:10)
    at Object.exports.singleRun (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/cli/run-helpers.js:207:16)
    at exports.runMocha (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/cli/run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/cli/run.js:296:3)
    at Object.runCommand (/z/aolney/repos/question-classifier-2003-reboot/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/z/aolney/repos/question-classifier-2003-reboot/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/z/aolney/repos/question-classifier-2003-reboot/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/cli/cli.js:63:6)
    at Object.<anonymous> (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! Test failed.  See above for more details.
```
Changing the mocha line back to the repo version replaces the above error with another error:

```
> mocha test-build -t 10000

/z/aolney/repos/question-classifier-2003-reboot/node_modules/yargs/yargs.js:1163
      else throw err
           ^

ReferenceError: document is not defined
    at Elmish_Program.setState$$1 [as setState] (/z/aolney/repos/question-classifier-2003-reboot/test-build/Fable.Elmish.React.3.0.1/react.js:48:103)
    at ProgramModule$$$runWith (/z/aolney/repos/question-classifier-2003-reboot/test-build/Fable.Elmish.3.0.0/program.js:187:15)
    at ProgramModule$$$run (/z/aolney/repos/question-classifier-2003-reboot/test-build/Fable.Elmish.3.0.0/program.js:201:3)
    at Object.<anonymous> (/z/aolney/repos/question-classifier-2003-reboot/test-build/src/App.js:237:34)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/z/aolney/repos/question-classifier-2003-reboot/test-build/Tests.js:28:12)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at /z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/mocha.js:330:36
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/mocha.js:327:14)
    at Mocha.run (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/mocha.js:804:10)
    at Object.exports.singleRun (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/cli/run-helpers.js:207:16)
    at exports.runMocha (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/cli/run-helpers.js:300:13)
    at Object.exports.handler.argv [as handler] (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/cli/run.js:296:3)
    at Object.runCommand (/z/aolney/repos/question-classifier-2003-reboot/node_modules/yargs/lib/command.js:242:26)
    at Object.parseArgs [as _parseArgs] (/z/aolney/repos/question-classifier-2003-reboot/node_modules/yargs/yargs.js:1087:28)
    at Object.parse (/z/aolney/repos/question-classifier-2003-reboot/node_modules/yargs/yargs.js:566:25)
    at Object.exports.main (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/lib/cli/cli.js:63:6)
    at Object.<anonymous> (/z/aolney/repos/question-classifier-2003-reboot/node_modules/mocha/bin/_mocha:10:23)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
npm ERR! Test failed.  See above for more details.
```
It seems in this case that the stub package and `withReactBatched` are needed.

**Comment by alfonsogarciacaro** [comment]
Hmm, looking at the errors this seems to be related to the fact you're running mocha with node.js instead of a browser (so things like `window.document` are undefined). Maybe you can try [running Mocha on the browser](https://mochajs.org/#running-mocha-in-the-browser)?

**Comment by aolney** [comment]
Great suggestion! I will have to read up on that - I'm new to mocha and had no idea it could run in the browser

**Comment by alfonsogarciacaro** [comment]
I guess you can also use a headless browser but I've not much experience with that. Pinging @Zaid-Ajaj because we were also talking about adding instructions to run tests in the browser with [Fable.Mocha](https://github.com/Zaid-Ajaj/Fable.Mocha/).

**Comment by Zaid-Ajaj** [comment]
Working on it, I need to play with it a lot more to write comprehensive docs. Especially with respect to React/Elmish. PR's are welcome too :)

**Comment by Zaid-Ajaj** [comment]
> we were also talking about adding instructions to run tests in the browser with Fable.Mocha.

Done! See [Running tests inside headless browser](https://github.com/Zaid-Ajaj/Fable.Mocha/#running-the-tests-using-headless-browser) for more detailed.

Let me know if you have any questions

**Comment by aolney** [comment]
Nice :+1:
