### ISSUE TITLE
Hitting an EPIPE error on `fable-loader/index.js`

### ISSUE THREAD

**Issue by OmanF** [fable-compiler/fable2-samples#23]
_Metadata_:
OS: Linux Debian Sid
.Net Core SDK: 3.1.101
Node.js: 10.17.0
NPM: 6.13.4

_Issue_:
* I cloned the repo
* Went to the `minimal` folder
* Ran `npm install` from CLI
* Ran `npm start`

Got the following stack trace, ending in an `EPIPE` error on `fable-loader/index.js` (BTW, I saw issue #7 but it seems for that user updating the .Net Core SDK did the trick while I'm already on latest):

```

ℹ ｢wds｣: Project is running at http://localhost:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./public
fable-compiler 2.3.19
child proccess errored: It was not possible to find any compatible framework version
The framework 'Microsoft.NETCore.App', version '2.1.0' was not found.
  - The following frameworks were found:
      3.1.1 at [/home/ohadfk/dotnet/shared/Microsoft.NETCore.App]

You can resolve the problem by installing the specified framework and/or SDK.

The specified framework can be found at:
  - https://aka.ms/dotnet-core-applaunch?framework=Microsoft.NETCore.App&framework_version=2.1.0&arch=x64&rid=debian-x64

✖ ｢wdm｣: Hash: 662a85a732cbe13657dc
Version: webpack 4.39.2
Time: 476ms
Built at: 01/21/2020 7:50:44 AM
    Asset     Size  Chunks             Chunk Names
bundle.js  360 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[0] multi (webpack)-dev-server/client?http://localhost:8080 ./src/App.fsproj 40 bytes {main} [built]
[./node_modules/ansi-html/index.js] 4.16 KiB {main} [built]
[./node_modules/html-entities/index.js] 231 bytes {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://localhost:8080] (webpack)-dev-server/client?http://localhost:8080 4.29 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.85 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {main} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./src/App.fsproj] 312 bytes {main} [built] [failed] [1 error]
    + 18 hidden modules

ERROR in ./src/App.fsproj
Module build failed (from ./node_modules/fable-loader/index.js):
Error: write EPIPE
    at Loader.command.then.catch.err (/home/ohadfk/coding_projects/fsharp/fable2-samples/minimal/node_modules/fable-loader/index.js:147:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
ℹ ｢wdm｣: Failed to compile.
```

**Note**: I ran the same set of commands on my work machine, a Windows 10 machine with both .Net 4.8 installed, but using .Net Core 3.0.0 and everything worked out just right...

**Comment by OmanF** [comment]
Looks like the solution, much like the one in #7, **indeed is** to "update" the `.Net Core` SDKs... only in my case, it was installing another SDK, the `.Net Core 2.1 (LTS)` SDK. 

Apparently, multiple SDKs can "live" on the same machine.

All is good now. Closing.
