### ISSUE TITLE
EPIPE error

### ISSUE THREAD

**Issue by aolney** [fable-compiler/fable2-samples#7]
May be related to https://github.com/elmish/sample-react-counter/issues/4

```
aolney@monkmonk:~/minimal$ npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

added 569 packages from 309 contributors and audited 8902 packages in 4.464s
found 0 vulnerabilities

aolney@monkmonk:~/minimal$ npx webpack-dev-server
ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./public
fable-compiler 2.1.12
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)
```

Some information about my set up

```
aolney@monkmonk:~$ mono --version
Mono JIT compiler version 5.18.1.0 (tarball Fri Mar 15 20:45:47 UTC 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           __thread
	SIGSEGV:       altstack
	Notifications: epoll
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(600)
	Suspend:       preemptive
	GC:            sgen (concurrent by default)
aolney@monkmonk:~$ dotnet --info
.NET Command Line Tools (2.1.200)

Product Information:
 Version:            2.1.200
 Commit SHA-1 hash:  2edba8d7f1

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.1.200/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.7
  Build    : 2d61d0b043915bc948ebf98836fefe9ba942be11

aolney@monkmonk:~$ node --version
v10.15.3
```

I've found some discussion about this [being a problem in some image scenarios](https://stackoverflow.com/questions/53681041/webpack-build-fails-with-epipe-error-linux-subsystem-only) and [an old node error](https://github.com/nodejs/node/issues/947) but neither seems to apply in this case.

**Comment by alfonsogarciacaro** [comment]
Hmm, I've never seen this. Is it happening every time? Can you please update to latest fable-compiler and see if it changes something?

**Comment by aolney** [comment]
Nothing changed with updating unfortunately

```
aolney@monkmonk:~/minimal$ npm install fable-compiler@latest
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

+ fable-compiler@2.2.3
updated 1 package and audited 8902 packages in 3.373s
found 0 vulnerabilities

aolney@monkmonk:~/minimal$ npx webpack-dev-server
ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./public
fable-compiler 2.2.3
events.js:174
      throw er; // Unhandled 'error' event
      ^

Error: write EPIPE
    at WriteWrap.afterWrite [as oncomplete] (net.js:779:14)
Emitted 'error' event at:
    at onwriteError (_stream_writable.js:431:12)
    at onwrite (_stream_writable.js:456:5)
    at _destroy (internal/streams/destroy.js:40:7)
    at Socket._destroy (net.js:604:3)
    at Socket.destroy (internal/streams/destroy.js:32:8)
    at WriteWrap.afterWrite [as oncomplete] (net.js:781:10)
```

I decided to upgrade my dotnet SDK following the [instructions here](https://dotnet.microsoft.com/download/linux-package-manager/ubuntu18-04/sdk-current). My reasoning was that the [fable 2.1 changes where fable communicates with node via stdin/stdout](https://twitter.com/fablecompiler/status/1068117649136254982?lang=en) could cause pipe issues.

The above instructions seem to have done a side by side install instead of upgrade, but the end result is that the problems was solved (at least also with using the latest compiler). Thanks for your help :+1: 

```
aolney@monkmonk:~/minimal$ dotnet --info
.NET Core SDK (reflecting any global.json):
 Version:   2.2.202
 Commit:    8a7ff6789d

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  18.04
 OS Platform: Linux
 RID:         ubuntu.18.04-x64
 Base Path:   /usr/share/dotnet/sdk/2.2.202/

Host (useful for support):
  Version: 2.2.3
  Commit:  6b8ad509b6

.NET Core SDKs installed:
  2.1.200 [/usr/share/dotnet/sdk]
  2.2.202 [/usr/share/dotnet/sdk]

.NET Core runtimes installed:
  Microsoft.AspNetCore.All 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.All]
  Microsoft.AspNetCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 2.0.7 [/usr/share/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 2.2.3 [/usr/share/dotnet/shared/Microsoft.NETCore.App]

To install additional .NET Core runtimes or SDKs:
  https://aka.ms/dotnet-download
aolney@monkmonk:~/minimal$ npx webpack-dev-serverℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./public
fable-compiler 2.2.3
/home/aolney/minimal/src> dotnet restore App.fsproj

Welcome to .NET Core!
---------------------
Learn more about .NET Core: https://aka.ms/dotnet-docs
Use 'dotnet --help' to see available commands or visit: https://aka.ms/dotnet-cli-docs

Telemetry
---------
The .NET Core tools collect usage data in order to help us improve your experience. The data is anonymous and doesn't include command-line arguments. The data is collected by Microsoft and shared with the community. You can opt-out of telemetry by setting the DOTNET_CLI_TELEMETRY_OPTOUT environment variable to '1' or 'true' using your favorite shell.

Read more about .NET Core CLI Tools telemetry: https://aka.ms/dotnet-cli-telemetry

ASP.NET Core
------------
Successfully installed the ASP.NET Core HTTPS Development Certificate.
To trust the certificate run 'dotnet dev-certs https --trust' (Windows and macOS only). For establishing trust on other platforms refer to the platform specific documentation.
For more information on configuring HTTPS see https://go.microsoft.com/fwlink/?linkid=848054.
  Restore completed in 3.13 sec for /home/aolney/minimal/src/App.fsproj.


Parsing ./src/App.fsproj...
fable: Compiled src/App.fsproj
fable: Compiled src/App.fs
fable: Compiled .fable/Fable.Elmish.React.2.2.0/react.fs
fable: Compiled .fable/Fable.Elmish.2.0.0/program.fs
fable: Compiled .fable/Fable.Elmish.2.0.0/prelude.fs
fable: Compiled .fable/Fable.Elmish.React.2.2.0/common.fs
fable: Compiled .fable/Fable.Elmish.2.0.0/cmd.fs
ℹ ｢wdm｣: Hash: 814a45594c7d3bfaabce
Version: webpack 4.29.6
Time: 11912ms
Built at: 04/06/2019 9:01:31 AM
    Asset     Size  Chunks             Chunk Names
bundle.js  1.7 MiB    main  [emitted]  main
Entrypoint main = bundle.js
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/App.fsproj 40 bytes {main} [built]
[./.fable/Fable.Elmish.2.0.0/program.fs] 5.47 KiB {main} [built]
[./.fable/Fable.Elmish.React.2.2.0/react.fs] 2.48 KiB {main} [built]
[./.fable/fable-library.2.2.3/Reflection.js] 7.14 KiB {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080] (webpack)-dev-server/client?http://0.0.0.0:8080 8.1 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./node_modules/webpack/hot/emitter.js] (webpack)/hot/emitter.js 75 bytes {main} [built]
[./src/App.fs] 1.63 KiB {main} [built]
[./src/App.fsproj] 25 bytes {main} [built]
    + 45 hidden modules
ℹ ｢wdm｣: Compiled successfully.
```
